<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/niklaslundberg/Arbor.Docker</PackageProjectUrl>
    <RepositoryUrl>https://github.com/niklaslundberg/Arbor.Docker</RepositoryUrl>
    <Copyright>Niklas Lundberg</Copyright>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Arbor.Processing" Version="1.0.0-build.1767869796" />
    <PackageReference Include="Serilog" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
    <_Parameter1>Arbor.Docker.WebApi</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Arbor.Hosting\Arbor.Hosting.csproj" />
  </ItemGroup>

</Project>